[help]
response = [
    "```",
    "I can do a lot of things! Here's a list of commands I can respond to:",
    "   love you - Responds with a random love message",
    "       Example: cc love you",
    "   slap @target - Responds with a random slap message aimed at the @target user",
    "       Example: cc slap @ChatCats",
    "       Example: cc please slap @ChatCats",
    "   slaps - Shows the User's effective slaps on @targets",
    "   stats - Responds with some stats about the bot and the chatters",
    "   help - Responds with this message",
    "```",
]

[profanity]
bad_words = ["fuck", "fck", "cock", "cck", "god", "jesus", "jeeesus", "jeesus", "vok", "poes", "bliksem"]
replacements = ["<:VivAngy:953143421915246702>",  "<:ThankYou:953823811499860058>", "<:gotcha:842666223871066122>", "<:foxsit:842296829344743474>", "<:foxhead:842297150746132481>", "<:foxdance:842297123332292628>", "<:Foxscared:842665201160683520>"]

[love]
responses = [
    "i love you too!! ❤️❤️❤️",
    "this is a bit awkward... i really do like you but i think i am in love with ... hmm i rather not say. sorry 😿",
    "<Insert loving message for the chatter that loves you here>",
    "You know that tingly little feeling you get when you like someone? That is your common sense leaving your body.",
    "I want someone who will look at me the same way I look at chocolate cake.",
    "I love you with all my belly. I would say heart, but my belly is bigger.",
    "You want to know who I'm in love with? Read the first word again.",
    "I love you so much I'd fight a bear for you. Well not a grizzly bear because they have claws, and not a panda bear because they know Kung Fu. But a care bear, I'd definitely fight a care bear for you.",
    "Will you lend me a kiss? I promise to give it back.",
    "Forget the butterflies, I feel the entire zoo in my stomach when I'm with you!",
    "Good thing I brought my library card because I'm totally checking you out.",
    "I love you more than coffee, but please don't make me prove it.",
    "I want to be the reason you look down at your phone and smile. Then walk into a pole.",
    "Besides chocolate, you're my favorite.",
    "I think you are suffering from a lack of vitamin ME.",
    "I love you even when I'm really, really hungry.",
    "I love you more than cake, and I really love cake.",
    "Relationships are like a walk in the park. Jurassic Park.",
    "I love you enough to make our iPhone-Samsung relationship work.",
    "All you need is love. But a little chocolate now and then doesn't hurt.",
    "Before i answer, please use a computer with slow Internet service so that I can see who you really are.",
]

[slap]
actions = [
    "slaps",
    "pokes",
    "tickles",
    "strokes",
    "boops",
    "touches",
    "throws",
    "attacks",
    "backhands",
    "shurikens",
    "hadoukens",
    "kamehamehas",
    "FUS ROH DAHs",
]
objects = [
    "a wet noodle",
    "a smelly fish",
    "a piece of cake",
    "a bag of angry cats",
    "a bag of howling foxes",
    "a fox tail attached to an angry fox",
    "a slice of pineapple pizza",
    "an agry pink chihuahua",
    "a 4 hour loadshedding",
    "a pink flamingo",
    "a giganotosaurus",
    "a raging pikachu",
]
body_parts = [
    "across the face",
    "on the hand",
    "between the eyes",
    "under the feet",
    "on the nose",
    "in the nostril",
    "on the bum bum",
    "on the back",
]
results = [
    "it is very effective",
    "!!!but it missed",
    "!!!<@> brushes it off like nothing",
    "!!!it is not effective at all",
    "<@> stumbles",
    "<@> faints",
    "<@> runs around screaming about bottled water",
    "!!!<@> sneezes",
    "!!!<@> laughs",
    "<@> starts a monolouge on how to exact revenge for this outrage",
    "<@> releases the inner villain",
    "<@> screams MORTAL COMBAT!",
    "<@> just gets obliterated",
]